FROM ruby:3.4.2-alpine

ARG RAILS_ROOT=/financial_api
ARG PACKAGES="nano openssl-dev postgresql-dev build-base curl git postgresql-client bash libpq-dev yaml-dev tzdata linux-headers"

RUN apk update \
    && apk upgrade \
    && apk add --update --no-cache $PACKAGES

RUN mkdir $RAILS_ROOT
WORKDIR $RAILS_ROOT

COPY Gemfile Gemfile.lock ./

ENV BUNDLE_PATH=/bundle_cache \
    GEM_HOME=/bundle_cache \
    GEM_PATH=/bundle_cache \
    BUNDLE_JOBS=4 \
    BUNDLE_RETRY=3

RUN bundle install

COPY . $RAILS_ROOT

EXPOSE 3000
CMD ["bundle", "exec", "rails", "s", "-b", "0.0.0.0", "-p", "3000"]